platform :ios, '8.0'
inhibit_all_warnings!
target 'kuaileNew' do

pod 'AFNetworking'
pod 'SDWebImage', '~>3.7'
pod 'Reachability'
pod 'MJRefresh'
pod 'MJExtension'
#pod 'ReactiveCocoa', '~> 2.5'
pod 'ReactiveObjC', '~> 2.1.0'
#pod 'ReactiveViewModel'
pod 'CMPopTipView'
pod 'FDFullscreenPopGesture'
pod 'iOS-QR-Code-Encoder'
pod 'SDCycleScrollView'
pod 'EAIntroView'
pod 'IQKeyboardManager'
pod 'WZLBadge'
pod 'JZLocationConverter'
pod 'BaiduMapKit'
pod 'BMKLocationKit'
pod 'SVProgressHUD'
#pod 'MJPhotoBrowser'
pod 'YLGIFImage'
pod 'JGProgressHUD'
pod 'TZImagePickerController'
pod 'YYKit'
pod 'Masonry'
end
